language: python

# set Python versions to be tested on
python:
  # - 3.6
  - 3.7
  - 3.8

# install and update pip, clone bandit repo
before_install:
  - echo "Upgrading pip"
  - python3 -m pip install --upgrade pip
  - git clone https://github.com/TravisToolbox/bandit

# install all required libraries and dependancies
install:
  - echo "Install project dependancies and requirements"
  - python3 -m pip install setuptools wheel twine
  - pip3 install codecov
  - pip3 install coverage
  - pip3 install pytest
  - pip3 install pytest-cov
  - pip install flake8 pytest
  - python3 setup.py install          # install aaindex dependancies
  - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  - ./bandit/install.sh               # install bandit

script:
  # - cd aaindex
  - echo "Running unit tests..."
  - python3 -m unittest discover
  - echo "Running pytest tests..."
  - python3 -m pytest tests/
  - echo "Running flake8 tests..."
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  - echo "Running Bandit tests..."
  # - ./bandit/scan.sh
  - echo "Running coverage report..."
  - pytest --cov-report term --cov=aaindex tests/
  # - pytest --flake8
  # - pytest --pylint
  # - coverage run -m unittest discover -s tests -p 'test_*.py' #  OR"coverage run -m unittest discover -s . -p '*_unit_test.py'"

after_success:
  # - codecov
  - coveralls
  - echo "Build success"
